version: "1"
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1213"
      POSTGRES_DB: ppks
      volumes:
        - ./ppks.sql:/docker-entrypoint-initdb.d/ppks.sql

  app:
    container_name: wa_bot_container
    restart: on-failure
    build: .
    image: wa_bot_image
    depends_on:
      - db
    ports:
      - "3001:3000"
